# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pcGkUDBR5P3g1PTR4Gh7lJWodxHZ14BS
"""

# Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Scikit-learn tools for model building and evaluation
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Load California Housing dataset (alternative to Boston)
from sklearn.datasets import fetch_california_housing

# Fetch the data
data = fetch_california_housing()

# Create a DataFrame with feature names
df = pd.DataFrame(data.data, columns=data.feature_names)

# Add target (housing prices) to the DataFrame
df['Price'] = data.target

# Display the first few rows of the DataFrame
df.head()

X = df[['MedInc','HouseAge','AveRooms']]
y = df['Price']

x_trin, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
df.head()

from google.colab import files
files.download('filename.ext')  # Replace with your file name